#!/usr/bin/env python

#
# (c) Jez Halford <hello@jezhalford.com>
#

import argparse
import sys

parser = argparse.ArgumentParser(description='Show specified lines from a file.')

parser.add_argument('-a', dest='a', action='store', 
    help='The starting line number (Optional - defaults to the first line)',
    default=1, type=int)

parser.add_argument('-b', dest='b', action='store',
    help='The ending line number (Optional - defaults to the last line)',
    default=None, type=int)

parser.add_argument('--line-nums', dest='nums', action='store_true',
    help='Show line numbers',
    default=False)

parser.add_argument('file', action='store',
    help='The file whose lines you want to see',
    nargs='?', metavar='FILE')

arguments = parser.parse_args()

if arguments.file == None:
    parser.print_help()
    exit(1)

if arguments.b == None:
    arguments.b = arguments.a+1
    endless = True
else:
    endless = False

if arguments.a > arguments.b:
    print "The starting line must be before the ending line."
    exit(2)

position = 1;

try:
    f = open(arguments.file, 'r')

except IOError as e:
    print "Can't open file " + arguments.file
    exit(3)

for line in f:
    if position >= arguments.a and position <= arguments.b:

        if arguments.nums:
            sys.stdout.write("\033[94m" + str(position) + ":  \033[0m")

        sys.stdout.write(line)

    if position > arguments.b:
        break

    position +=1

    if endless:
        arguments.b = position + 1

f.close()
